# SPDX-FileCopyrightText:  NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3"
services:
  app:
    image: node:12
    volumes:
      - ./:/code
    working_dir: /code
    command: npm run start
    ports:
      - "8999:8080"
    tty: true
