# version 1.0
# added lint (lines 20:21)
name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: install
        run: npm install

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build
