name: CI/CD

on:
  push:
  pull_request:

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: noi-techpark/github-actions/npm-build@v2
        with:
          build-command: npm run build
          node-version: ${{env.NODE_VERSION}}
